services:
  kometa:
    image: lscr.io/linuxserver/kometa
    container_name: kometa
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - KOMETA_TIME=07:20 #optional
      - KOMETA_RUN=False #optional
      - KOMETA_CONFIG=/config/config.yml #optional
      - KOMETA_TEST=False #optional
      - KOMETA_NO_MISSING=False #optional
    volumes:
      - ./config:/config
    restart: unless-stopped

#cd /home/jhn/Docker/containers/Kometa
#sudo docker-compose up -d

#docker pull kometateam/kometa
#sudo docker-compose up -d
