#####################################################
#                  NETWORKS 6.0                     #
#####################################################

templates:
  network:
    smart_filter:
      sort_by: release.desc
      validate: false
      any:
        network: <<network>>
    sort_title: zzzzzz_<<collection_name>>

  streaming:
    smart_filter:
      sort_by: release.desc
      validate: false
      any:
        network: <<network>>
    sort_title: ++++_<<collection_name>>

# Fetched from TMDb using the studio id and/or name
collections:
  ABC:
    template: { name: network, network: "ABC, ABC Family" }
    file_poster: config/posters/ABC.png
    visible_shared:
      - monthly(28)
      - monthly(29)
      - monthly(30)
      - monthly(31)
    studio: ABC, ABC (AU), ABC (US), ABC Studios, ABC1

  Adult Swim:
    template: { name: network, network: "Adult Swim" }
    file_poster: config/posters/Adult Swim.png

  AMC:
    template: { name: network, network: "AMC, AMC+" }
    file_poster: config/posters/AMC.png
    studio: AMC, AMC Networks, AMC Studios, AMC+, American Movie Classics (AMC)
    visible_shared:
      - monthly(25)
      - monthly(26)
      - monthly(27)

  A&E:
    template: { name: network, network: "A&E" }
    file_poster: config/posters/A&E.png
    studio: A&E

  BBC:
    template:
      {
        name: network,
        network: "BBC America, BBC Four, BBC One, BBC Two, BBC Three",
      }
    file_poster: config/posters/BBC.png
    visible_shared:
      - monthly(25)
      - monthly(26)
      - monthly(27)
    studio: BBC, BBC America, BBC Natural History Unit, BBC One, BBC Two, BBC Three, BBC Wales, British Brodcasting Corporation (BBC)

  Cartoon Network:
    template: { name: network, network: "Cartoon Network" }
    file_poster: config/posters/Cartoon Network.png
    studio: Cartoon Network Studios
    visible_shared:
      - monthly(19)
      - monthly(20)
      - monthly(21)

  CBS:
    template: { name: network, network: "CBS, CBS All Access" }
    file_poster: config/posters/CBS.png
    visible_shared:
      - monthly(22)
      - monthly(23)
      - monthly(24)
    studio: CBS, CBS Sony Group Inc., CBS Studios, CBS Television Studios

  Cinemax:
    template: { name: network, network: "Cinemax" }
    file_poster: config/posters/Cinemax.png
    studio: Cinemax

  Comedy Central:
    template: { name: network, network: "Comedy Central" }
    file_poster: config/posters/Comedy Central.png

  Discovery+:
    template: { name: network, network: "Discovery, Discovery+" }
    file_poster: config/posters/Discovery+.png
    studio: Discovery Channel, Discovery Channel (CA)

  Epix:
    template: { name: network, network: Epix }
    file_poster: config/posters/Epix.png
    studio: EPIX, Epix, Epix (I)

  FOX:
    template: { name: network, network: "FOX, Fox Kids" }
    file_poster: config/posters/Fox.png
    visible_shared:
      - monthly(10)
      - monthly(11)
      - monthly(12)
    studio: 20th Century Fox Television, 30th Century Fox Television, FOX, Fox 21, Fox 21 Televsion Studios, Fox Productions, Fox Television Productions

  Freeform:
    template: { name: network, network: "Freeform" }
    file_poster: config/posters/Freeform.png
    studio: Freeform

  FX:
    template: { name: network, network: "FX, FXX" }
    file_poster: config/posters/FX.png
    studio: FX, FX Productions, FXX
    visible_shared:
      - monthly(16)
      - monthly(17)
      - monthly(18)

  History*:
    template: { name: network, network: "History" }
    file_poster: config/posters/History..png
    studio: History

  MTV:
    template: { name: network, network: "MTV, MTV2" }
    file_poster: config/posters/MTV.png
    studio: MTV, MTV Entertainment Studios, MTV Networks

  National Geographic:
    template: { name: network, network: "National Geographic" }
    file_poster: config/posters/National Geographic.png
    studio: National Geographic

  Nickelodeon:
    template: { name: network, network: "Nickelodeon, Nicktoons" }
    file_poster: config/posters/Nickelodeon.png
    studio: Nickelodeon Animation Studio, Nickelodeon Productions

  NBC:
    template: { name: network, network: "NBC" }
    file_poster: config/posters/NBC.png
    visible_shared:
      - monthly(10)
      - monthly(11)
      - monthly(12)
    studio: NBC, NBCUniversal International Studios

  Showtime:
    template: { name: network, network: "Showtime" }
    file_poster: config/posters/Showtime.png
    visible_shared:
      - monthly(4)
      - monthly(5)
      - monthly(6)
    studio: Showtime, Showtime Documentary Films, Showtime Networks

  Starz:
    template: { name: network, network: "Starz" }
    file_poster: config/posters/Starz.png
    visible_shared:
      - monthly(28)
      - monthly(29)
      - monthly(30)
      - monthly(31)
    studio: Starz, Starz Productions

  Syfy:
    template: { name: network, network: "Syfy" }
    file_poster: config/posters/Syfy.png
    visible_shared:
      - monthly(7)
      - monthly(8)
      - monthly(9)
    studio: Syfy

  SVT:
    template: { name: network, network: "SVT1, SVT Play" }
    file_poster: config/posters/SVT.png

  TBS:
    template: { name: network, network: "TBS" }
    file_poster: config/posters/TBS.png
    studio: TBS

  YouTube:
    template: { name: network, network: "YouTube, YouTube Premium" }
    file_poster: config/posters/YouTube.png
    studio: Youtube Premium

  USA:
    template: { name: network, network: "USA Network" }
    file_poster: config/posters/USA.png
    visible_shared:
      - monthly(1)
      - monthly(2)
      - monthly(3)
    studio: USA Networks

  TNT:
    template: { name: network, network: "TNT" }
    file_poster: config/posters/TNT.png
    studio: TNT (USA)

  The CW:
    template: { name: network, network: "The CW" }
    file_poster: config/posters/The CW.png
    studio: The CW

  ##########################################################
  #                   STREAMING 3.0                        #
  ##########################################################

  # Original TV shows from the most popular streaming services
  Apple TV+:
    template: { name: streaming, network: "Apple TV+" }
    file_poster: config/posters/Apple TV+.png
    studio: Apple, Apple TV+
    visible_shared:
      - monthly(1)
      - monthly(2)
      - monthly(3)

  Disney+:
    template: { name: streaming, network: "Disney Channel, Disney XD, Disney+" }
    file_poster: config/posters/Disney+.png
    studio: Disney Television Animation, Disney+, Walt Disney Pictures, Walt Disney Television
    visible_shared:
      - monthly(22)
      - monthly(23)
      - monthly(24)

  HBO Max:
    template: { name: streaming, network: "HBO, HBO Max, Max" }
    file_poster: config/posters/HBO Max.png
    studio: HBO, HBO Entertainment, HBO Films, Home Box Office (HBO)
    visible_shared:
      - monthly(13)
      - monthly(14)
      - monthly(15)

  Hulu:
    template: { name: streaming, network: "Hulu" }
    file_poster: config/posters/HULU.png
    studio: Hulu
    visible_shared:
      - monthly(7)
      - monthly(8)
      - monthly(9)

  Netflix:
    template: { name: streaming, network: "Netflix" }
    file_poster: config/posters/Netflix.png
    studio: Netflix
    visible_shared:
      - monthly(16)
      - monthly(17)
      - monthly(18)

  Paramount+:
    template:
      {
        name: streaming,
        network: "Paramount+, Paramount Network, Paramount+ with Showtime",
      }
    file_poster: config/posters/Paramount+.png
    visible_shared:
      - monthly(4)
      - monthly(5)
      - monthly(6)
    studio: Paramount+, Paramount Television Studios

  Peacock:
    template: { name: streaming, network: "Peacock" }
    file_poster: config/posters/Peacock.png
    visible_shared:
      - monthly(13)
      - monthly(14)
      - monthly(15)

  Prime Video:
    template: { name: streaming, network: "Prime Video" }
    file_poster: config/posters/Prime Video.png
    studio: Amazon Prime Video
    visible_shared:
      - monthly(19)
      - monthly(20)
      - monthly(21)
